--- 
addons: 
  apt: 
    packages: 
      - openjdk-8-jdk
app: sia-5
before_install: 
  - "chmod +x mvnw"
deploy: 
  api-key: 
    secure: $HEROKU_API_KEY
  provider: heroku
dist: trusty
jdk: openjdk8
language: java
sudo: true