language: java
sudo: true
dist: trusty
jdk: openjdk8 
addons:
  apt:
    packages:
      - openjdk-8-jdk
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
 app: sia-5
